name: Build and Deploy Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, ARM64]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t jahongir98/devops-app:latest .

      - name: Deploy container
        run: |
          docker stop devops-app || true
          docker rm devops-app || true
          docker run -d -p 80:80 --name devops-app jahongir98/devops-app:latest
